### ISSUE TITLE
Add a way to make page content backups as well as the ability to  restore to previous versions. 

### ISSUE THREAD

**Issue by yulolimum** [infinitered/thesis-phoenix#101]
This can be an addition to the import/export code. We can reuse some of the code to serialize the page data on save. We'll need a migration and a new endpoint to save the data.

**Comment by agustif** [comment]
Im guessing you're not a fan of adding third party dependencies, and seeing this as an alternative to exAdmin bloated code, but smpallen has [whatwasit](https://github.com/smpallen99/whatwasit) and example using it along with coherence called [store](https://github.com/smpallen99/store).

There's is also [paper_trail](https://github.com/airblade/paper_trail) for further reference, but maybe the rails way is not the best elixir way...

**Comment by yulolimum** [comment]
@agustif - this is actually a very interesting suggestion. The goal with thesis is to have a very minimalistic approach to everything, from the editor itself to the models, from the number of deps to the code. I think whatwasit or something similar could be a potential solution if Thesis starts getting more complex in nature or we do a rewrite of the endpoints to support versioning (with the right library). Expanding on the import/export branch we just recently merged, I was able to achieve entire page versioning with 2 simple endpoints and a few lines of React (will have a branch available for testing soon). 

But perhaps I'm not seeing the benefits of something more robust? IMO, it's better to write and plug in something simple that works and can be scrapped/replaced later then to base core functionality on an outside dep.

**Comment by agustif** [comment]
Sure, probably you're right, since right now your use case involves already-trusted users, your employees, stuff like knowing who and when made one edit, or being able to rollback all edit from a user, are not needed for now.

I actually think your approach of simple is best, and maintaing deps to a minimum too, I love to peek on github's repos and issues, and it seems with the new path for phoenix 1.3 still not yet paved, people is like in a freeze-dont-move state until things fall to its place.

Anyway, thanks for the open source!

**Comment by jamonholmgren** [comment]
@yulolimum Can you give an update on this?

**Comment by yulolimum** [comment]
@jamonholmgren You and I actually have been attempting to pair on this for the past few weeks. I need to wrap up the tests but am getting a very weird error.

**Comment by yulolimum** [comment]
Working on some tests for this.
