### ISSUE TITLE
Rethink how React manipulates non-React components

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/thesis-phoenix#39]
I'm not super happy with how we are currently handling non-React components. I'd like to research best practices and come up with some ideas on how we could improve / streamline it.

Examples, most of which should use state, not reach into the DOM:

https://github.com/infinitered/thesis-phoenix/blob/master/web/static/js/thesis-editor.js#L46-L47
https://github.com/infinitered/thesis-phoenix/blob/master/web/static/js/thesis-editor.js#L94 
https://github.com/infinitered/thesis-phoenix/blob/master/web/static/js/thesis-editor.js#L131
https://github.com/infinitered/thesis-phoenix/blob/master/web/static/js/content_types/html_editor.js#L7

Perhaps there could be an object outside of the React component that does the dirty DOM queries and gives those as props to the ThesisEditor component. From then on, it's all self-contained.

Thoughts, @kemiller @GantMan @yulianglukhenko @ryanlntn @skellock ?

**Comment by danielberkompas** [comment]
Are you using `document` functions because the DOM elements you want to manipulate aren't within the element you're rendering to with `ReactDOM`?

**Comment by jamonholmgren** [comment]
@danielberkompas Correct. While I'm using (and liking) React for the editor, the content editors themselves (HTML, text, image) live (at least partially) outside of the React component. This isn't a huge problem in and of itself, but I want to more easily achieve "UI as a function of state" regardless.

**Comment by jamonholmgren** [comment]
Here's my idea:

```
Thesis - plain JS object that collects all DOM objects and info and creates ThesisEditor
  |
  |-- ThesisEditor - React component that takes as props everything that Thesis needs and renders the React components
      |
      |-- HTMLEditor/TextEditor/etc - plain JS objects that handle updating non-React DOM objects
```

**Comment by kemiller** [comment]
Sounds like you just want some piece that will fill in the gaps in "dirty code" that would be given to you by the react renderer.  I.e. you want bridge that isolates the peeking and poking at the dom and lets your react component stay pure.

**Comment by jamonholmgren** [comment]
I think I'll "wrap" the React component, so I can inject the dirty parts into the component and React never does any `document.querySelectorAll` calls.

**Comment by skellock** [comment]
You won't get "UI as a function of state" because you're not in control of all the editors.  But I think that's just semantics.  You can certain achieve "UI controlled by state".

And honestly, you're pretty damn close as is.  Knowing nothing about your implementation details I was able to read your code right away.

So, what I've learned with React is:  keep pushing things up.  It will buy you time as you figure out the right architecture for you.  I'm all-in on dumb components these days.

Your plan to have Thesis as a top level entry point with the DOM lookups is great and `ThesisEditor` will become cleaner with your proposed approach.

Push up your "events" too.  Don't let your `*Editors` tell `ThesisEditor` what to do.

For example:

https://github.com/infinitered/thesis-phoenix/blob/master/web/static/js/content_types/html_editor.js#L37

This can be triggered with a function.  So `ThesisEditor` hands each of the `*Editors` a function they can call when it's time to report dirty state.

My $0.02 Canadian.

**Comment by jamonholmgren** [comment]
Good stuff, @skellock. I thought about handing in a function as well to the editors (you can see my multiple `TODO: stop being stupid` comments), so that's great reinforcement. Will be working on this soonish.

**Comment by jamonholmgren** [comment]
This still needs additional work, but I'm no longer very worried about it before release. I'll leave the Version 1.0 milestone on it, but I think 0.1 can be released without additional refactoring. We really need JS tests before we can get too crazy with this anyway.
